logging:
    file:
        name: /tmp/adminservice.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://lemur-17.cloud-iam.com/auth/realms/inftfy
                    jwk-set-uri: https://lemur-17.cloud-iam.com/auth/realms/inftfy/protocol/openid-connect/certs
datasource:
        url: jdbc:postgresql://localhost:5432/inftfy
        username: postgres
        password: postgres
        jpa:
            hibernate:
                ddl-auto: update
        jackson:
            serialization:
                fail-on-empty-beans: false
app:
    config:
        keycloak:
            server-url: https://lemur-17.cloud-iam.com/auth/
            realm: iNFTFy
            clientId: adminclient
            client-secret: dwCbxaieLCrRGI0HoHwc6fQV4biTX9Cr
            ssl-required: none