eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://lemur-18.cloud-iam.com/auth/realms/inftfy
                    jwk-set-uri: https://lemur-18.cloud-iam.com/auth/realms/inftfy/protocol/openid-connect/certs