logging:
    file:
        name: /tmp/adminservice.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9191/realms/iNFTFy
                    jwk-set-uri: http://localhost:9191/realms/iNFTFy/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://localhost:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        serialization:
            fail-on-empty-beans: false
app:
    config:
        keycloak:
            server-url: http://localhost:9191
            realm: iNFTFy
            clientId: realm-management
            client-secret: Cn1e1NvET1z5BOt9DvvBrwQOApiuF95t