logging:
    file:
        name: /tmp/adminservice.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://auth.cognologix.in/realms/iNFTFy
                    jwk-set-uri: https://auth.cognologix.in/realms/iNFTFy/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://localhost:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show-sql: true
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        serialization:
            fail-on-empty-beans: false
app:
    config:
        keycloak:
            server-url: https://auth.cognologix.in/
            realm: iNFTFy
            clientId: adminclient
            client-secret: gNZxcTxRRjno67RkrmIsj7l5bN0K6lCG