logging:
    file:
        name: /tmp/apigateway.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://auth.cognologix.in/realms/iNFTFy
                    jwk-set-uri: https://auth.cognologix.in/realms/iNFTFy/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://localhost:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        serialization:
            fail-on-empty-beans: false
app:
    config:
        keycloak:
            server-url: https://lemur-15.cloud-iam.com/auth
            realm: infinity
            clientId: realm-management
            client-secret: zZD5mf2momTkFIalTEFOxWV6EggWzQ37