eureka:
    instance:
        hostname: blockchainservice
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://discovery:8761/eureka/
        eureka-service-url-poll-interval-seconds: 15
spring:
    application:
        name: blockchainservice
    profiles:
        active: '@activatedProperties@'
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    main:
        allow-bean-definition-overriding: true
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        serialization:
            fail-on-empty-beans: false
server:
    port: 8105
    error:
        include-message: always
        include-binding-errors: always
        include-exception: false

wallet:
    testnetrpcurl: https://rpc-mumbai.maticvigil.com/
    testnetpk: 7b0a7c69ac5994a016fdbae128e89558cc55206542711ec84860b7cd362d5d27
    testnettoken: 0xbcd480f7839fe5b1174125dc7cd5a891c2cadda3
    testnetchainId: 80001
