eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}
logging:
    file:
        name: /tmp/core-api-gateway.log
    logstash:
        enabled: true
        url: logstash:5000
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9191/realms/iNFTFy
                    jwk-set-uri: http://localhost:9191/realms/iNFTFy/protocol/openid-connect/certs
