logging:
    file:
        name: /tmp/nft-studio-service.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://${KCHOST}:${KCPORT}/realms/${KCREALM}
                    jwk-set-uri: http://${KCHOST}:${KCPORT}/realms/${KCREALM}/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://localhost:5432/inftfy
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        serialization:
            fail-on-empty-beans: false
app:
    config:
        keycloak:
            server-url: http://${KCHOST}:${KCPORT}
            realm: ${KCREALM}
            clientId: ${KCCLIENT}
            client-secret: Ed7lbLueleOKm5lob0genakG3SGQ52gw