eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}
logging:
    file:
        name: /tmp/studio-auth-gateway.log
    logstash:
        enabled: true
        url: logstash:5000
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    rabbitmq:
        addresses: amqp://rabbitmq:5672/
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://auth-server:9999/auth/realms/3cn
                    jwk-set-uri: http://auth-server:9999/auth/realms/3cn/protocol/openid-connect/certs
    zipkin:
        base-url: http://zipkin:9411/
