logging:
    file:
        name: /tmp/studio-auth-gateway.log
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://lemur-18.cloud-iam.com/auth/realms/iNFTFy
                    jwk-set-uri: https://lemur-18.cloud-iam.com/auth/realms/iNFTFy/protocol/openid-connect/certs
